import { p1, p2, p3, p4, p5, p6, p7, p8, p9, p10 } from "./Images/index.js";
import { p11, p12, p13, p14, p15, p16, p17, p18, p19 } from "./Images/index.js";
import { p20, p21, p22, p23, p24, p25, p26, p27, p28 } from "./Images/index.js";
import { p29, p30, p31, p32, p33, p34, p35, p36, p37 } from "./Images/index.js";
import { p38, p39, p40, p41, p42, p43, p44, p45, p46 } from "./Images/index.js";
import { p47, p48, p49, p50, p51, p52, p53, p54, p55 } from "./Images/index.js";
import { p56, p57, p58, p59, p60, p61, p62, p63, p64 } from "./Images/index.js";
import { p65, p66, p67, p68, p69, p70, p71, p72, p73 } from "./Images/index.js";

const productsData = [
  {
    id: "price_1OPpNlI1zNR8sZYDlf1fyOxc",
    imageSrc: p73,
    title: "Custom Design",
    price: "199.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p1,
    title: "Como Tu No Hay Otra",
    price: "149.99",
  },
  {
    id: "price_1OPpPgI1zNR8sZYDZwOqYbbu",
    imageSrc: p2,
    title: "Anniversary White",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p3,
    title: "NutCracker Pink",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p4,
    title: "History Huh?",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p5,
    title: "Pink Princess",
    price: "149.99",
  },

  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p6,
    title: "Birthday Cream ",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p7,
    title: "Birthday Dior Red",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p8,
    title: "Birthday Betty Boop",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p9,
    title: "Ginger Bread",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p10,
    title: "Pink Flower Pot",
    price: "149.99",
  },
  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p11,
    title: "Anniversary Photos",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p12,
    title: "Princess & the Frog",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p13,
    title: "BTS Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p14,
    title: "Birthday Red ",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p15,
    title: "Teddy&Flowers",
    price: "149.99",
  },
  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p16,
    title: "Red Roses",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p17,
    title: "21st Crown Birthday",
    price: "149.99",
  },
  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p18,
    title: "Casate Conmigo?",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p19,
    title: "Medical Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p20,
    title: "Lilo & Stitch",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p21,
    title: "Birthday Pink/White",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p22,
    title: "Feliz Dia Mama",
    price: "149.99",
  },

  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p23,
    title: "Winnie Pooh-photos",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p24,
    title: "Como Tu No Hay Otra",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p25,
    title: "Sister Birtday",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p26,
    title: "Planet Earth",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p27,
    title: "Roses Blue/White",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p28,
    title: "Fall Bouqet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p29,
    title: "Birthday Winnie Pooh",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p30,
    title: "PinkBow WhiteRose",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p31,
    title: "BDay PinkWhite",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p32,
    title: "Birthday Butterflies",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p33,
    title: "Money Hat",
    price: "149.99",
  },
  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p34,
    title: "Scream in Pink",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p35,
    title: "Bday Fall Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p36,
    title: "HomeComing?",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p37,
    title: "Don Julio",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p38,
    title: "Shades of Blue",
    price: "149.99",
  },

  {
    id: "price_1OMEvyI1zNR8sZYDu7Iv8yqk",
    imageSrc: p39,
    title: "Butterfly Roses",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p40,
    title: "Hello Kitty Basket",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p41,
    title: "Evil Hello Kitty",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p42,
    title: "SpiderVerse",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p43,
    title: "16th Birthday",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p44,
    title: "Hello Kitty Birthday",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p45,
    title: "Mama Chingona",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p46,
    title: "Chucky Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p47,
    title: "Te Amo ",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p48,
    title: "Be My Devil",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p49,
    title: "White Pink Butterflies",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p50,
    title: "Love You To Death",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p51,
    title: "Birthday For Mom",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p52,
    title: "Forever My Boo",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p53,
    title: "Lottey Hat",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p54,
    title: "Blue Scream",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p55,
    title: "Michael Myers",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p56,
    title: "Malibu Pink",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p57,
    title: "Thank You Bouquet",
    price: "149.99",
  },
  {
    id: "price_1OMEy0I1zNR8sZYD2Przz5fx",
    imageSrc: p58,
    title: "Pink Bat Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p59,
    title: "Purple White Gold",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p60,
    title: "BDay Money Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p61,
    title: "Red Roses",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p62,
    title: "Smirnoff Bouquet ",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p63,
    title: "Modelo Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p64,
    title: "Red Roses Butterflies",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p65,
    title: "Halloween",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p66,
    title: "Big Money Bouquet",
    price: "199.99",
  },
  {
    id: "  ",
    imageSrc: p67,
    title: "Birthday Violet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p68,
    title: "BDay PinkWhite",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p69,
    title: "Yello/Blue Butterflies",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p70,
    title: "Middle Pink Rose",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p71,
    title: "Alcohol Bouquet",
    price: "149.99",
  },
  {
    id: "  ",
    imageSrc: p72,
    title: "RedGold Butterflies",
    price: "149.99",
  },
];

export default productsData;
